# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a39df12afc613fa358ef0e88e014d76c94ef7139ce2bb9b8febfeb33bd630e0772128ed4f1e686001dbf4ccde9ed2ef91ed831b03b803fad7052211205913a27

test:
  secret_key_base: 55d4a17ed58268242fad0a4d13185ef2fb5030592b9d7d81ab47e84deee24dab4fb3421d4f53b5c450af5b7ad8349faa1b49ebcbc8f5c8af0fb5b606376f10a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
